name: Latest YouTube Videos
on:
  schedule:
    - cron: "0 * * * *"
  workflow_dispatch:

jobs:
  update-readme-with-youtube:
    name: Update this repo's README with latest videos from YouTube
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@master
        with:
          comment_tag_name: "YOUTUBE"
          feed_list: "https://www.youtube.com/feeds/videos.xml?channel_id=UCFBAMSjeJOmQ-gLrqczjRbg"
          template: '<article style="display:flex;"><a href="$url" rel="nofollow"><img width="140px" src="https://i.ytimg.com/vi/$videoId/mqdefault.jpg" data-canonical-src="https://i.ytimg.com/vi/PkT0MieM9dM/mqdefault.jpg" /></a>$newline<div><a href="https://i.ytimg.com/vi/$videoId/mqdefault.jpg" rel="nofollow">$title</a><p>$date</p></div>$newline</article>$newline'

